//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorManager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class SesnorManagerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SesnorManagerSettings defaultInstance = ((SesnorManagerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SesnorManagerSettings())));
        
        public static SesnorManagerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Myproject\\configSensorsFile.txt")]
        public string Configfile {
            get {
                return ((string)(this["Configfile"]));
            }
        }
    }
}
